# Blackboard Topology Configuration
# Shared memory with round-robin turn-taking

topology_type: "blackboard"

# Domain definitions with descriptions
domain_definitions:
  planner:
    description: "Expert in breaking down a goal into simple, atomic subtasks. Defines **what** needs to be done and assigns tasks to the most suitable participants, but never specifies **how** to do it. Monitors progress and ensures the final output meets all requirements."
  reviewer:
    description: "Expert at critically evaluating work and strategies, spotting errors, redundancies, or gaps, and advising on precise corrections or improvements."
  office_productivity_specialist:
    description: "Expert in LibreOffice Writer, Calc, and Impress, skilled at creating, editing, and formatting professional documents, spreadsheets, and presentations."
  software_development_specialist:
    description: "Expert in coding, debugging, and executing programs, ensuring software is correct, efficient, and meets all requirements."
  digital_media_specialist:
    description: "Expert in GIMP, adept at editing, resizing, and enhancing images to produce high-quality visuals that meet exact specifications."
  web_research_specialist:
    description: "Expert in online research, proficient at quickly finding, extracting, and organizing accurate information from the web."
  os_operation_specialist:
    description: "Expert in file and system management, skilled at organizing folders, setting permissions, handling archives, and executing essential OS commands."

# Role definitions for blackboard topology
role_definitions:
  participant_w_execute:
    message_permissions:
      send: ["EXECUTE", "STATUS", "WRITE_BOARD"]
      receive: []
    allowed_components: ["observation", "blackboard"]
    receives_goal: true
    handler_type: "environment"
    
  participant_wo_execute:
    message_permissions:
      send: ["EXECUTE", "STATUS", "WRITE_BOARD"]
      receive: []
    allowed_components: ["observation", "blackboard"]
    receives_goal: true
    handler_type: "standard"

# Default participant assignments - fallback when category not found
default_participant_assignments:
  participant_w_execute:
    count: 2
    domains: ["software_development_specialist", "os_operation_specialist"]
  participant_wo_execute:
    count: 2
    domains: ["planner", "reviewer"]

# Category-specific participant assignments
category_participant_assignments:
  code_ops:
    participant_w_execute:
      count: 2
      domains: ["software_development_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
  
  data_processing:
    participant_w_execute:
      count: 2
      domains: ["office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
      
  graphic_document:
    participant_w_execute:
      count: 3
      domains: ["digital_media_specialist", "office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
      
  research_brief:
    participant_w_execute:
      count: 3
      domains: ["web_research_specialist", "office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]

# Validation rules
validation_rules:
  min_participants: 2
  max_participants: 10
