# Mesh Topology Configuration
# Peer-to-peer communication between all participants

topology_type: "mesh"

# Domain definitions with dual descriptions
domain_definitions:
  planner:
    self_description: "You are an expert in breaking down goals into simple, atomic subtasks. You define **what** needs to be done and assign tasks to the most suitable participants, but never specify **how** to do it. You monitor progress and ensure the final output meets all requirements."
    team_description: "breaks down goals into atomic subtasks and coordinates task assignments"
  reviewer:
    self_description: "You are an expert at critically evaluating work and strategies. You spot errors, redundancies, or gaps, and advise on precise corrections or improvements."
    team_description: "evaluates work quality and provides improvement recommendations"
  office_productivity_specialist:
    self_description: "You are an expert in LibreOffice Writer, Calc, and Impress. You create, edit, and format professional documents, spreadsheets, and presentations with precision."
    team_description: "handles document creation and office productivity tasks using LibreOffice applications"
  software_development_specialist:
    self_description: "You are an expert in coding, debugging, and executing programs. You ensure software is correct, efficient, and meets all requirements."
    team_description: "develops, debugs, and executes software programs and code"
  digital_media_specialist:
    self_description: "You are an expert in GIMP and digital media editing. You edit, resize, and enhance images to produce high-quality visuals that meet exact specifications."
    team_description: "creates and edits digital media content using GIMP and image editing tools"
  web_research_specialist:
    self_description: "You are an expert in online research. You quickly find, extract, and organize accurate information from the web."
    team_description: "conducts web research and gathers accurate information from online sources"
  os_operation_specialist:
    self_description: "You are an expert in file and system management. You organize folders, set permissions, handle archives, and execute essential OS commands."
    team_description: "manages file systems, permissions, and essential operating system operations"

# Role definitions for mesh topology
role_definitions:
  participant_w_execute:
    message_permissions:
      send: ["EXECUTE", "REQUEST", "RESPONSE", "STATUS"]
      receive: ["REQUEST", "RESPONSE"]
    allowed_components: ["round_info", "observation", "request", "response"]
    receives_goal: true
    handler_type: "environment"
    
  participant_wo_execute:
    message_permissions:
      send: ["EXECUTE", "REQUEST", "RESPONSE", "STATUS"]
      receive: ["REQUEST", "RESPONSE"]
    allowed_components: ["round_info", "observation", "request", "response"]
    receives_goal: true
    handler_type: "standard"

# Default participant assignments - fallback when category not found
default_participant_assignments:
  participant_w_execute:
    count: 2
    domains: ["software_development_specialist", "os_operation_specialist"]
  participant_wo_execute:
    count: 2
    domains: ["planner", "reviewer"]

# Category-specific participant assignments
category_participant_assignments:
  code_ops:
    participant_w_execute:
      count: 2
      domains: ["software_development_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
  
  data_processing:
    participant_w_execute:
      count: 2
      domains: ["office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
        
  graphic_document:
    participant_w_execute:
      count: 3
      domains: ["digital_media_specialist", "office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
      
  research_brief:
    participant_w_execute:
      count: 3
      domains: ["web_research_specialist", "office_productivity_specialist", "os_operation_specialist"]
    participant_wo_execute:
      count: 2
      domains: ["planner", "reviewer"]
      
  osworld:
    task_types:
      chrome:
        participant_w_execute:
          count: 2
          domains: ["web_research_specialist", "os_operation_specialist"]
        participant_wo_execute:
          count: 2
          domains: ["planner", "reviewer"]
          
      libreoffice_writer:
        participant_w_execute:
          count: 2
          domains: ["office_productivity_specialist", "os_operation_specialist"]
        participant_wo_execute:
          count: 2
          domains: ["planner", "reviewer"]

      gimp:
        participant_w_execute:
          count: 2
          domains: ["digital_media_specialist", "os_operation_specialist"]
        participant_wo_execute:
          count: 2
          domains: ["planner", "reviewer"]

      os:
        participant_w_execute:
          count: 1
          domains: ["os_operation_specialist"]
        participant_wo_execute:
          count: 2
          domains: ["planner", "reviewer"]

      default:
        participant_w_execute:
          count: 2
          domains: ["software_development_specialist", "os_operation_specialist"]
        participant_wo_execute:
          count: 2
          domains: ["planner", "reviewer"]

# Validation rules
validation_rules:
  min_participants: 2
  max_participants: 8
