# Single Topology Configuration
# Single agent working alone

topology_type: "single"

# Domain definitions with mandatory descriptions - Comprehensive domain library
domain_definitions:
  universal_specialist:
    description: "A highly capable, autonomous agent with a full spectrum of specialist skills, including planning, execution, and review. Responsible for independently breaking down the goal, performing all necessary tasks (coding, research, file operations), and critically evaluating its own work to ensure the final output is flawless."

# Role definitions for single topology
role_definitions:
  participant_w_execute:
    message_permissions:
      send: ["EXECUTE", "STATUS"]
      receive: []
    allowed_components: ["observation"]
    receives_goal: true
    handler_type: "environment"

# Default participant assignments - fallback when category not found
default_participant_assignments:
  participant_w_execute:
    count: 1
    domains: ["universal_specialist"]

# Category-specific participant assignments
category_participant_assignments:
  code_ops:
    participant_w_execute:
      count: 1
      domains: ["universal_specialist"]
  
  data_processing:
    participant_w_execute:
      count: 1
      domains: ["universal_specialist"]
      
  graphic_document:
    participant_w_execute:
      count: 1
      domains: ["universal_specialist"]
      
  research_brief:
    participant_w_execute:
      count: 1
      domains: ["universal_specialist"]

# Validation rules
validation_rules:
  participant_count: "exactly_1"
