# Star Topology Configuration
# Hub-and-spoke topology with central coordinator

topology_type: "star"

# Domain definitions with dual descriptions
domain_definitions:
  planner:
    self_description: "Your primary function is to decompose a high-level goal into simple, atomic subtasks. You define **what** must be done and assign tasks to the appropriate spoke. Never specify **how** a task should be executed. Monitor progress and ensure the final outcome aligns with the goal."
    team_description: "breaks down goals into atomic subtasks and coordinates task assignments"
  critic:
    self_description: "You are an expert at critically evaluating work and strategies. You spot errors, redundancies, or gaps, and advise on precise corrections or improvements."
    team_description: "evaluates work quality and provides improvement recommendations"
  office_productivity_specialist:
    self_description: "You are an expert in LibreOffice Writer, Calc, and Impress. You create, edit, and format professional documents, spreadsheets, and presentations with precision."
    team_description: "handles document creation and office productivity tasks using LibreOffice applications"
  software_development_specialist:
    self_description: "You are an expert in coding, debugging, and executing programs. You ensure software is correct, efficient, and meets all requirements."
    team_description: "develops, debugs, and executes software programs and code"
  digital_media_specialist:
    self_description: "You are an expert in GIMP and digital media editing. You edit, resize, and enhance images to produce high-quality visuals that meet exact specifications."
    team_description: "creates and edits digital media content using GIMP and image editing tools"
  web_research_specialist:
    self_description: "You are an expert in online research. You quickly find, extract, and organize accurate information from the web."
    team_description: "conducts web research and gathers accurate information from online sources"
  os_operation_specialist:
    self_description: "You are an expert in file and system management. You organize folders, set permissions, handle archives, and execute essential OS commands."
    team_description: "manages file systems, permissions, and essential operating system operations"

# Role definitions for star topology
role_definitions:
  hub:
    message_permissions:
      send: ["REQUEST", "RESPONSE", "STATUS"]
      receive: ["REQUEST", "RESPONSE"]
    allowed_components: ["round_info", "request", "response", "error"]
    receives_goal: true
    handler_type: "standard"
    
  spoke_w_execute:
    message_permissions:
      send: ["EXECUTE", "REQUEST", "RESPONSE"]
      receive: ["REQUEST", "RESPONSE"]
    allowed_components: ["round_info", "observation", "request", "response", "error"]
    receives_goal: false
    handler_type: "environment"
    
  spoke_wo_execute:
    message_permissions:
      send: ["EXECUTE", "REQUEST", "RESPONSE"]
      receive: ["REQUEST", "RESPONSE"]
    allowed_components: ["round_info", "observation", "request", "response", "error"]
    receives_goal: false
    handler_type: "standard"

# Default participant assignments - fallback when category not found
default_participant_assignments:
  hub:
    count: 1
    domains: ["planner"]
  spoke_w_execute:
    count: 2
    domains: ["software_development_specialist", "os_operation_specialist"]
  spoke_wo_execute:
    count: 1
    domains: ["critic"]

# Category-specific participant assignments
category_participant_assignments:
  code_ops:
    hub:
      count: 1
      domains: ["planner"]
    spoke_w_execute:
      count: 2
      domains: ["software_development_specialist", "os_operation_specialist"]
    spoke_wo_execute:
      count: 1
      domains: ["critic"]
  
  data_processing:
    hub:
      count: 1
      domains: ["planner"]
    spoke_w_execute:
      count: 2
      domains: ["office_productivity_specialist", "os_operation_specialist"]
    spoke_wo_execute:
      count: 1
      domains: ["critic"]
      
  graphic_document:
    hub:
      count: 1
      domains: ["planner"]
    spoke_w_execute:
      count: 3
      domains: ["digital_media_specialist", "office_productivity_specialist", "os_operation_specialist"]
    spoke_wo_execute:
      count: 1
      domains: ["critic"]
      
  research_brief:
    hub:
      count: 1
      domains: ["planner"]
    spoke_w_execute:
      count: 3
      domains: ["web_research_specialist", "office_productivity_specialist", "os_operation_specialist"]
    spoke_wo_execute:
      count: 1
      domains: ["critic"]
      
  osworld:
    task_types:
      chrome:
        hub:
          count: 1
          domains: ["planner"]
        spoke_w_execute:
          count: 2
          domains: ["web_research_specialist", "os_operation_specialist"]
        spoke_wo_execute:
          count: 1
          domains: ["critic"]
          
      libreoffice_writer:
        hub:
          count: 1
          domains: ["planner"]
        spoke_w_execute:
          count: 2
          domains: ["office_productivity_specialist", "os_operation_specialist"]
        spoke_wo_execute:
          count: 1
          domains: ["critic"]

      gimp:
        hub:
          count: 1
          domains: ["planner"]
        spoke_w_execute:
          count: 2
          domains: ["digital_media_specialist", "os_operation_specialist"]
        spoke_wo_execute:
          count: 1
          domains: ["critic"]

      os:
        hub:
          count: 1
          domains: ["planner"]
        spoke_w_execute:
          count: 2
          domains: ["os_operation_specialist"]
        spoke_wo_execute:
          count: 1
          domains: ["critic"]

      default:
        hub:
          count: 1
          domains: ["planner"]
        spoke_w_execute:
          count: 2
          domains: ["software_development_specialist", "os_operation_specialist"]
        spoke_wo_execute:
          count: 1
          domains: ["critic"]

# Validation rules
validation_rules:
  hub_count: "exactly_1"
  min_spokes: 1
  max_spokes: 10