# Star Topology Configuration
# Hub-and-spoke topology with central coordinator

topology_type: "star"

# Domain definitions with descriptions
domain_definitions:
  planner:
    self_description: "You are an expert in breaking down goals into simple, atomic subtasks. You define **what** needs to be done and assign tasks to the most suitable participants, but never specify **how** to do it. You monitor progress and ensure the final output meets all requirements."
    team_description: "Task coordinator who breaks down goals into manageable subtasks and assigns them to appropriate team members."
  reviewer:
    self_description: "You are an expert at critically evaluating work and strategies. You spot errors, redundancies, or gaps, and advise on precise corrections or improvements."
    team_description: "Quality assurance specialist who evaluates work and provides improvement recommendations."
