# Unified Configuration for Computer Game Instance Generator
# This file contains ALL configuration needed for the system

# Task Generation Configuration
task_generation:
  experiments:
    shared:
      shared_code_maintenance_l1:
        sampling:
          - category: "code_maintenance"
            levels: [1]
            instances_per_task: 1
        output:
          upload_s3: true
          output_dir: "outputs"
          session_name: "shared_code_maintenance_l1"
      shared_code_maintenance_l2:
        sampling:
          - category: "code_maintenance"
            levels: [2]
            instances_per_task: 1
        output:
          upload_s3: true
          output_dir: "outputs"
          session_name: "shared_code_maintenance_l2"

    individual:
      single_agent_a11y_tree_l1:
        use_shared: "shared_code_maintenance_l1"
      single_agent_screenshot_a11y_tree_l1:
        use_shared: "shared_code_maintenance_l1"
      single_agent_screenshot_l1:
        use_shared: "shared_code_maintenance_l1"
      multi_agent_star_screenshot_l1:
        use_shared: "shared_code_maintenance_l1"
      multi_agent_star_screenshot_a11y_tree_l1:
        use_shared: "shared_code_maintenance_l1"
      single_agent_a11y_tree_l2:
        use_shared: "shared_code_maintenance_l2"
      single_agent_screenshot_a11y_tree_l2:
        use_shared: "shared_code_maintenance_l2"
      single_agent_screenshot_l2:
        use_shared: "shared_code_maintenance_l2"
      multi_agent_star_screenshot_l2:
        use_shared: "shared_code_maintenance_l2"
      multi_agent_star_screenshot_a11y_tree_l2:
        use_shared: "shared_code_maintenance_l2"
      multi_agent_blackboard_screenshot_l1:
        use_shared: "shared_code_maintenance_l1"
      multi_agent_blackboard_screenshot_a11y_tree_l1:
        use_shared: "shared_code_maintenance_l1"
      multi_agent_mesh_screenshot_l1:
        use_shared: "shared_code_maintenance_l1"
      multi_agent_mesh_screenshot_a11y_tree_l1:
        use_shared: "shared_code_maintenance_l1"

# Experiment Configuration
experiments:
  # Single Agent Experiments (Level 1)
  single_agent_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Multi-Agent Experiments (Level 1)
  multi_agent_star_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"] # TODO: change domains to something meaningful in context of Ubuntu environment.
    
  multi_agent_star_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]

  # Single Agent Experiments (Level 2)
  single_agent_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_l2:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Multi-Agent Experiments (Level 1, 2)
  multi_agent_star_screenshot_l2:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"] # TODO: change domains to something meaningful in context of Ubuntu environment.
    
  multi_agent_star_screenshot_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]

  # Blackboard Topology Experiments
  multi_agent_blackboard_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "blackboard"
    participants:
      executor:
        count: 3
        domains: ["Farmer", "Developer", "Task Coordination"]
    
  multi_agent_blackboard_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "blackboard"
    participants:
      executor:
        count: 3
        domains: ["Farmer", "Developer", "Task Coordination"]

  # Mesh Topology Experiments
  multi_agent_mesh_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "mesh"
    participants:
      executor:
        count: 3
        domains: ["web automation", "file management", "system administration"]
    
  multi_agent_mesh_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "mesh"
    participants:
      executor:
        count: 3
        domains: ["Thinker", "Python", "Orchestrator"]

# System Configuration
system:
  vm_path: "/Users/nidhirbhavsar/Desktop/WORK/OSWorld/vmware_vm_data/Ubuntu0/Ubuntu0.vmx"
  screen_width: 1920
  screen_height: 1080
  max_rounds: 10
  max_transitions_per_round: 20
  player_consecutive_violation_limit: 3
  player_total_violation_limit: 5
  sliding_window_size: null

# Role Configurations
roles:
  single:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "STATUS"]
        receive: []
      allowed_components: ["observation"]
      receives_goal: true

  star:
    advisor:
      name: "advisor"
      handler_type: "standard"
      message_permissions:
        send: ["REQUEST", "RESPONSE", "STATUS"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["request", "response"]
      receives_goal: true
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "REQUEST", "RESPONSE"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["observation", "request", "response"]
      receives_goal: false

  blackboard:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "STATUS", "WRITE_BOARD"]
        receive: []
      allowed_components: ["observation", "blackboard"]
      receives_goal: true

  mesh:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "REQUEST", "RESPONSE", "STATUS"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["observation", "request", "response"]
      receives_goal: true