# Unified Configuration for Computer Game Instance Generator
# This file contains ALL configuration needed for the system

# Task Generation Configuration
task_generation:
  experiments:
    shared:
      default_code_maintenance:
        sampling:
          - category: "code_maintenance"
            levels: [1]
            instances_per_task: 5
        output:
          upload_s3: true
          output_dir: "outputs"
          session_name: "default_code_maintenance"

    individual:
      single_agent_a11y_tree:
        use_shared: "default_code_maintenance"
      single_agent_screenshot_a11y_tree:
        use_shared: "default_code_maintenance"
      single_agent_screenshot:
        use_shared: "default_code_maintenance"
      multi_agent_star_screenshot:
        use_shared: "default_code_maintenance"
      multi_agent_star_screenshot_a11y_tree:
        use_shared: "default_code_maintenance"

# Experiment Configuration
experiments:
  # Single Agent Experiments
  single_agent_a11y_tree:
    environment_type: "osworld"
    observation_type: "a11y_tree"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_a11y_tree:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot:
    environment_type: "osworld"
    observation_type: "screenshot"
    participants:
      executor:
        count: 1
        domains: []

  # Multi-Agent Experiments
  multi_agent_star_screenshot:
    environment_type: "osworld"
    observation_type: "screenshot"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]
    
  multi_agent_star_screenshot_a11y_tree:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]

# System Configuration
system:
  vm_path: "/Users/nidhirbhavsar/Desktop/WORK/OSWorld/vmware_vm_data/Ubuntu0/Ubuntu0.vmx"
  screen_width: 1920
  screen_height: 1080
  max_rounds: 30
  max_transitions_per_round: 30
  player_consecutive_violation_limit: 3
  player_total_violation_limit: 5 