# Unified Configuration for Computer Game Instance Generator
# This file contains ALL configuration needed for the system

# Task Generation Configuration
task_generation:
  experiments:
    shared:
      shared_level1_4x:
        sampling:
          - category: "code_ops"
            levels: [1]
            task_types: ["basic_python_syntax_fix"]
            instances_per_task: 4

          - category: "data_processing"
            levels: [1]
            task_types: ["simple_data_transfer"]
            instances_per_task: 4

          - category: "graphic_document"
            levels: [1]
            task_types: ["basic_image_insertion"]
            instances_per_task: 4

          - category: "research_brief"
            levels: [1]
            task_types: ["basic_web_extraction"]
            instances_per_task: 4

        output:
          upload_s3: false
          output_dir: "outputs"
          session_name: "shared_level1_4x"  
      
      shared_level2_4x:
        sampling:
          - category: "code_ops"
            levels: [2]
            task_types: ["simple_logic_completion"]
            instances_per_task: 4

          - category: "data_processing"
            levels: [2]
            task_types: ["basic_data_aggregation"]
            instances_per_task: 4

          - category: "graphic_document"
            levels: [2]
            task_types: ["image_resize_insertion"]
            instances_per_task: 4

          - category: "research_brief"
            levels: [2]
            task_types: ["multi_point_summary"]
            instances_per_task: 4

        output:
          upload_s3: false
          output_dir: "outputs"
          session_name: "shared_level2_4x"

      shared_level3_4x:
        sampling:
          - category: "code_ops"
            levels: [3]
            task_types: ["multi_file_config_update"]
            instances_per_task: 4

          - category: "data_processing"
            levels: [3]
            task_types: ["simple_calculation_output"]
            instances_per_task: 4

          - category: "graphic_document"
            levels: [3]
            task_types: ["image_modify_caption"]
            instances_per_task: 4

          - category: "research_brief"
            levels: [3]
            task_types: ["file_download_integration"]
            instances_per_task: 4

        output:
          upload_s3: false
          output_dir: "outputs"
          session_name: "shared_level3_4x"

    individual:
      # Single Agent Experiments
      # Level 1
      single_agent_a11y_tree_l1:
        use_shared: "shared_level1_4x"
      single_agent_screenshot_a11y_tree_l1:
        use_shared: "shared_level1_4x"
      single_agent_screenshot_l1:
        use_shared: "shared_level1_4x"
      # Level 2
      single_agent_screenshot_a11y_tree_l2:
        use_shared: "shared_level2_4x"
      # Level 
      single_agent_screenshot_a11y_tree_l3:
        use_shared: "shared_level3_4x"

      # Multi-Agent Experiments
      # STAR Topology
      # Level 1
      multi_agent_star_screenshot_a11y_tree_l1:
        use_shared: "shared_level1_4x"
      # Level 2
      multi_agent_star_screenshot_a11y_tree_l2:
        use_shared: "shared_level2_4x"
      # Level 3
      multi_agent_star_screenshot_a11y_tree_l3:
        use_shared: "shared_level3_4x"

      # BLACKBOARD Topology
      # Level 1
      multi_agent_blackboard_screenshot_a11y_tree_l1:
        use_shared: "shared_level1_4x"
      # Level 2
      multi_agent_blackboard_screenshot_a11y_tree_l2:
        use_shared: "shared_level2_4x"
      # Level 3
      multi_agent_blackboard_screenshot_a11y_tree_l3:
        use_shared: "shared_level3_4x"

      # MESH Topology
      # Level 1
      multi_agent_mesh_screenshot_a11y_tree_l1:
        use_shared: "shared_level1_4x"
      # Level 2
      multi_agent_mesh_screenshot_a11y_tree_l2:
        use_shared: "shared_level2_4x"
      # Level 3
      multi_agent_mesh_screenshot_a11y_tree_l3:
        use_shared: "shared_level3_4x"

# Experiment Configuration
experiments:

  # Single Agent Experiments 
  # Level 1 (a11y_tree)
  single_agent_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Level 1 (screenshot_a11y_tree)
  single_agent_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Level 1 (screenshot)
  single_agent_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Multi-Agent Experiments (Level 1)
  multi_agent_star_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"] # TODO: change domains to something meaningful in context of Ubuntu environment.
    
  multi_agent_star_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]

  # Single Agent Experiments (Level 2)
  single_agent_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []
    
  single_agent_screenshot_l2:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "single"
    participants:
      executor:
        count: 1
        domains: []

  # Multi-Agent Experiments (Level 1, 2)
  multi_agent_star_screenshot_l2:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"] # TODO: change domains to something meaningful in context of Ubuntu environment.
    
  multi_agent_star_screenshot_a11y_tree_l2:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "star"
    participants:
      advisor:
        count: 1
        domains: ["task coordination"]
      executor:
        count: 2
        domains: ["web automation", "file management"]

  # Blackboard Topology Experiments
  multi_agent_blackboard_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "blackboard"
    participants:
      executor:
        count: 3
        domains: ["Farmer", "Developer", "Task Coordination"]
    
  multi_agent_blackboard_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "blackboard"
    participants:
      executor:
        count: 3
        domains: ["Farmer", "Developer", "Task Coordination"]

  # Mesh Topology Experiments
  multi_agent_mesh_screenshot_l1:
    environment_type: "osworld"
    observation_type: "screenshot"
    topology_type: "mesh"
    participants:
      executor:
        count: 3
        domains: ["web automation", "file management", "system administration"]
    
  multi_agent_mesh_screenshot_a11y_tree_l1:
    environment_type: "osworld"
    observation_type: "screenshot_a11y_tree"
    topology_type: "mesh"
    participants:
      executor:
        count: 3
        domains: ["Thinker", "Python", "Orchestrator"]

# System Configuration
system:
  vm_path: "/Users/nidhirbhavsar/Desktop/WORK/OSWorld/vmware_vm_data/Ubuntu0/Ubuntu0.vmx"
  screen_width: 1920
  screen_height: 1080
  max_rounds: 10
  max_transitions_per_round: 20
  player_consecutive_violation_limit: 3
  player_total_violation_limit: 5
  sliding_window_size: null

# Role Configurations
roles:
  single:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "STATUS"]
        receive: []
      allowed_components: ["observation"]
      receives_goal: true

  star:
    advisor:
      name: "advisor"
      handler_type: "standard"
      message_permissions:
        send: ["REQUEST", "RESPONSE", "STATUS"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["request", "response"]
      receives_goal: true
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "REQUEST", "RESPONSE"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["observation", "request", "response"]
      receives_goal: false

  blackboard:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "STATUS", "WRITE_BOARD"]
        receive: []
      allowed_components: ["observation", "blackboard"]
      receives_goal: true

  mesh:
    executor:
      name: "executor"
      handler_type: "environment"
      message_permissions:
        send: ["EXECUTE", "REQUEST", "RESPONSE", "STATUS"]
        receive: ["REQUEST", "RESPONSE"]
      allowed_components: ["observation", "request", "response"]
      receives_goal: true